Mindhaven/Models/UserSetting.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mindhaven.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public int UserId { get; set; }
        public Nullable<bool> ShowNotifications { get; set; }
        public Nullable<bool> EnableChat { get; set; }
        public Nullable<bool> ShowHistory { get; set; }
        public Nullable<bool> OfflineStatus { get; set; }
    }
}

Mindhaven/Controllers/UserSettingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Mindhaven.Helpers;
using Mindhaven.Models;

namespace Mindhaven.Controllers
{
    public class UserSettingsController : Controller
    {
        private readonly mindhavenDBEntities1 db = new mindhavenDBEntities1();

        // GET: UserSettings
        public ActionResult Index()
        {
            

            if (Session["UserId"] == null) return RedirectToAction("Login", "Account");
            int userId = Convert.ToInt32(Session["UserId"]);

            var settings = db.UserSettings.FirstOrDefault(s => s.UserId == userId);
            return View(settings);
        }

        // POST: Update settings
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update(UserSetting model)
        {

            if (Session["UserId"] == null) return RedirectToAction("Login", "Account");
            int userId = Convert.ToInt32(Session["UserId"]);

            var settings = db.UserSettings.FirstOrDefault(s => s.UserId == userId);
            if (settings != null)
            {
                settings.ShowNotifications = model.ShowNotifications;
                settings.EnableChat = model.EnableChat;
                settings.ShowHistory = model.ShowHistory;
                settings.OfflineStatus = model.OfflineStatus;

                db.Entry(settings).State = EntityState.Modified;
                await db.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }
    }
}

Mindhaven/Views/UserSettings/Create.cshtml
@model Mindhaven.Models.UserSetting

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserSetting</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShowNotifications, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ShowNotifications)
                    @Html.ValidationMessageFor(model => model.ShowNotifications, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnableChat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.EnableChat)
                    @Html.ValidationMessageFor(model => model.EnableChat, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShowHistory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ShowHistory)
                    @Html.ValidationMessageFor(model => model.ShowHistory, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OfflineStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.OfflineStatus)
                    @Html.ValidationMessageFor(model => model.OfflineStatus, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Mindhaven/Views/UserSettings/Delete.cshtml
@model Mindhaven.Models.UserSetting

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserSetting</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ShowNotifications)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShowNotifications)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnableChat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnableChat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShowHistory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShowHistory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OfflineStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OfflineStatus)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Mindhaven/Views/UserSettings/Details.cshtml
@model Mindhaven.Models.UserSetting

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>UserSetting</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ShowNotifications)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShowNotifications)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnableChat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnableChat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShowHistory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShowHistory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OfflineStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OfflineStatus)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UserId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Mindhaven/Views/UserSettings/Edit.cshtml
@model Mindhaven.Models.UserSetting

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserSetting</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserId)

        <div class="form-group">
            @Html.LabelFor(model => model.ShowNotifications, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ShowNotifications)
                    @Html.ValidationMessageFor(model => model.ShowNotifications, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnableChat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.EnableChat)
                    @Html.ValidationMessageFor(model => model.EnableChat, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShowHistory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ShowHistory)
                    @Html.ValidationMessageFor(model => model.ShowHistory, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OfflineStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.OfflineStatus)
                    @Html.ValidationMessageFor(model => model.OfflineStatus, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Mindhaven/Views/UserSettings/Index.cshtml
@model Mindhaven.Models.UserSetting

@{
    ViewBag.Title = "User Settings";
}

<h2>User Settings</h2>

@if (Model != null)
{
    <form method="post" action="@Url.Action("Update", "UserSettings")">
        @Html.AntiForgeryToken()

        <div>
            <label>
                <input type="checkbox" name="ShowNotifications" value="true" @(Model.ShowNotifications.GetValueOrDefault() ? "checked" : "") /> Show Notifications
            </label>
        </div>

        <div>
            <label>
                <input type="checkbox" name="EnableChat" value="true" @(Model.EnableChat.GetValueOrDefault() ? "checked" : "") /> Enable Chat
            </label>
        </div>

        <div>
            <label>
                <input type="checkbox" name="ShowHistory" value="true" @(Model.ShowHistory.GetValueOrDefault() ? "checked" : "") /> Show History
            </label>
        </div>

        <div>
            <label>
                <input type="checkbox" name="OfflineStatus" value="true" @(Model.OfflineStatus.GetValueOrDefault() ? "checked" : "") /> Offline Status
            </label>
        </div>

        <button type="submit">Save Settings</button>
    </form>
}
else
{
    <p>No settings found for your account.</p>
}